### ISSUE TITLE
Issues report

### ISSUE THREAD

**Issue by frantisekrusnak** [m2ms/fragalysis-frontend#3] opened 2020-02-03 15:43 UTC
As a user I want to report issues with the application.

**Comment by tibor-postek-m2ms** [comment] 2020-02-07 08:52
- capture screen after closing modal window with selecting screen
![image](https://user-images.githubusercontent.com/57392303/74014736-90665d00-498f-11ea-9ee5-6f02d6407bec.png)

**Comment by matej-vavrek** [comment] 2020-02-12 15:00
There is a button "Report issue" to report an issue.

**Comment by matej-vavrek** [comment] 2020-02-13 11:59
- [ ] Add also "Cancel" button alongside the "Proceed" in dialog

**Comment by veronikabelusikova** [comment] 2020-02-13 14:36
There are some parameters missing in dialog:
**_version_**
**_actual session state_** (is this solved by making screenshot?)
**_attachment_** - only screenshot is attached, but other attachment it is not possible to add,
_**Date and time**_

Report is submitted via a form located in the menu
- there is "Report error" item in menu, but when I click on it, only So_mething went wrong - unexpected error. Please contact Fragalysis support!_ window is displayed, not required dialog
- requirement also in documentation: The “_Something went wrong” dialog is not displayed if user want to report issue from menu option."_

Name and Email are not automatically filled, I have to enter them manually, also when I am logged in

**Comment by veronikabelusikova** [comment] 2020-02-17 12:44
**Actually done:** 
- Issue report (dialog) contains 
o	Version
o	Screenshot of the current page (without any modal dialogs or system / browser popups)
o	Name
o	Short description of the problem (title)
o	Description of the problem
o	Date and time
- A link to the issue is returned to the user after successful report submission and the issue creation in GitHub
- Report issue button (icon) should be placed at top bar.

**To do or to be discussed if it is required:** 
- Issue report (dialog) contains 
o	Actual session state
o	Email

- The Application shall fill Name and Email parameters for registered user --> I have to enter data manually
- Report is submitted via a form located in the menu --> there is no item in menu to report issue
- After a report submission is automatically created an issue in GitHub with its name, description and “bug” label --> issue has "issue" label, not "bug"

**Comment by phraenquex** [comment] 2020-03-05 18:55
The remaining issues look like a duplicate of the ticket I just created (#163).  So closing this ticket too - and anyway it's already in the release.

**Closed by phraenquex** 2020-03-05 18:55 UTC
Labels: Prio 1, Ver 0.1.0, task
