### ISSUE TITLE
Displayed vectors look wrong (to a chemist) - a Fragment Network issue?

### ISSUE THREAD

**Issue by fragalysis-reporter** [m2ms/fragalysis-frontend#157] opened 2020-03-04 13:56 UTC
- Version: 0.1.0
- Name: Anthony Aimon
- Description: This compound should have many green vectors, its a standard urea.
Any idea why all the vectors are red?
Thanks

Anthony

![screenshot](https://github.com/m2ms/fragalysis-assets/blob/master/screenshot-1583330159857114754.png?raw=true)

**Comment by phraenquex** [comment] 2020-03-05 06:17
Rachael, can you evaluate?  If it is a bug, then it's a priority issue.

**Comment by reskyner** [comment] 2020-03-05 08:54
Yep, it's a bug. If you click on the vectors, there are some compounds.

**Comment by phraenquex** [comment] 2020-03-10 14:28
Duplicate of #161 - close now.

**Closed by phraenquex** 2020-03-10 14:28 UTC
Labels: Prio 1, Ver 0.2.0, bug, issue
