### ISSUE TITLE
Selecting and reselecting sites - inconsistencies

### ISSUE THREAD

**Issue by boriskovar-m2ms** [m2ms/fragalysis-frontend#190] opened 2020-03-16 07:58 UTC
Select site, select vector on molecule, unselect site, select different site, reselect the firstly selected site.
Observed behavior: Vectors are displayed for given molecule, if vector is selected then compounds for given vector are also visible in compound picker. When the site is unselected the vectors disapear from ngl view, compounds stay visible. After reselecting the site the buttons are in state that vectors should be visible in NGL view.
Expected behavior: when site is deselected then all selected elements from given site should be deselected and cleared from NGL view (something like clear all button). Picked compounds should stay in "shopping cart".

**Comment by veronikabelusikova** [comment] 2020-03-26 13:05
tested on: 
https://fragalysis-tibor.apps.xchem.diamond.ac.uk/viewer/react/snapshot/c8eb9d57-d6f5-4826-9847-3e3860b85bda

**Comment by reskyner** [comment] 2020-03-30 13:24
This snapshot doesn't seem to work. It looks like the issue is solved on fragalysis.apps.xchem.diamond.ac.uk though. Please open PR

**Comment by phraenquex** [comment] 2020-03-30 16:18
Try this snapshot:  https://fragalysis-boris.apps.xchem.diamond.ac.uk/viewer/react/fragglebox/1fb9ebf8-30c2-48e5-b208-7200c9d8b894

**Comment by phraenquex** [comment] 2020-03-30 16:21
This almost works, one remaining bug:  it should be possible to view vectors for multiple ligands simultaneously - so don't turn off vectors automatically when I turn on other vectors.
But DO turn off vectors when I turn off the ligand.

**Comment by boriskovar-m2ms** [comment] 2020-03-31 06:55
This behavior is by design and is carried over from previous iteration of the UI. We can make it work in the way as you described if you wish so.

**Comment by phraenquex** [comment] 2020-03-31 07:59
Yes, please implement the change. Thanks

Sent from tiny silly touch screen
________________________________

**Comment by boriskovar-m2ms** [comment] 2020-03-31 08:19
I will create a new issue for this matter.

**Comment by phraenquex** [comment] 2020-03-31 09:35
No just fix it in this ticket please, and do so now - then we can get it 
out.

**Comment by boriskovar-m2ms** [comment] 2020-03-31 10:12
Ok

**Comment by boriskovar-m2ms** [comment] 2020-03-31 10:12
It should be possible to view vectors for multiple ligands. Toggling vector view for molecule should not toggle any other vector view toggle for any other molecule. However when switching off ligand view for molecule then also vector view for given molecule should be switched off if it was switched on.

**Comment by tibor-postek-m2ms** [comment] 2020-04-01 12:58
- [ ] improve usage of these properties in selectionReducers(for more than 1 vector):
- [ ] currentVector
- [ ]  to_query

**Comment by tibor-postek-m2ms** [comment] 2020-04-06 12:44
- [ ] Bug with reloading state from snapshot

**Comment by phraenquex** [comment] 2020-04-06 14:43
What are we meant to test on this issue?  I thought ithe fix had been deployed days ago.

**Comment by boriskovar-m2ms** [comment] 2020-04-06 14:48
Implementation of displaying vectors of multiple lignads was finnished only today because frontend was not prepared for it. I noticed a small bug and already wrote to Tibor about it.

**Comment by phraenquex** [comment] 2020-04-06 15:51
Okay.  Do we need to check anything before this is merged to production?  Please state what exactly.

**Comment by tibor-postek-m2ms** [comment] 2020-04-07 05:32
- [ ] BUG - select vector of molecu, select vector in NGL view, unselect ligant of given molecule, select another molecule and its vector and window compounds to pick is hidden

**Comment by tibor-postek-m2ms** [comment] 2020-04-07 11:34
- [ ] after deselecting vector in hit navigator (if current vector in given molecule) remove data from compounds to pick
- [ ] fix bug from video
[fragalysis.mp4.zip](https://github.com/m2ms/fragalysis-frontend/files/4443887/fragalysis.mp4.zip)

**Comment by tibor-postek-m2ms** [comment] 2020-04-08 11:37
- [ ] Bug  - infinity loop of error after click on share snapshot

**Comment by tibor-postek-m2ms** [comment] 2020-04-09 05:48
You can do test at https://fragalysis-matej.apps.xchem.diamond.ac.uk/viewer/react/snapshot/66e7f78f-3a7f-4c47-a8e9-626798aedba4

**Closed** 2020-04-09 06:06 UTC
Labels: Ver 0.6.0, bug
