### ISSUE TITLE
Button to turn all ligands/proteins/contacts on isn't working

### ISSUE THREAD

**Issue by reskyner** [m2ms/fragalysis-frontend#682] opened 2021-11-19 13:50 UTC
Since the sites changed to tags, the button at the top of the hit navigator have stopped working

**Comment by rsanchezgarc** [comment] 2021-12-21 18:07
If the users press the P or L button and then press it again before it finishes, then, it no longer works

**Comment by phraenquex** [comment] 2021-12-22 07:50
This one does not need to go into rel 2.6.3.  @boriskovar-m2ms please make the call - if it's not a quick win, change it to rel 2.6.5

But behaviour should be, apply L/P/C only to selected hits.  Then it will be well-behaved.

**Comment by ag-m2ms** [comment] 2022-01-14 11:17
The buttons are disabled both for the list and individual molecules (I managed to reproduce the issue on a single molecule as well). Clicking on a button (f.e. L) disables that button and potentially other button which might cause issue (f.e. the A button). I fixed the RHS as well.
I managed to track down the issue with performance when turning off all ligands. It should be fixed as well.
The solutions is in the #682-fix branch.

**Comment by phraenquex** [comment] 2022-01-14 11:47
Can you confirm what this means:  _"The buttons are disabled both for the list and individual molecules"_

Can you confirm that this is implemented:  _"But behaviour should be, apply L/P/C only to hits selected by the checkboxes. Then it will be well-behaved."_

Can you push this on the testing server?  (Is that still active, @boriskovar-m2ms ?)

**Comment by ag-m2ms** [comment] 2022-01-14 11:57
> Can you confirm what this means: "The buttons are disabled both for the list and individual molecules"

When NGL is in the process of displaying an item or items, related buttons to that item are disabled. The list buttons are the LPC buttons at the top of the molecule list, individual molecule buttons are ALPC.. buttons on each molecule in that list. For instance, if you click on L at the top of list, the L buttons on each molecule in the list are disabled. Also if you click on L on a molecule, it will disable the L, A buttons on the molecule and the L button at the top of the list, since they can tamper with the state while NGL is loading the data. Once NGL finished the buttons are reenabled.

> Can you confirm that this is implemented: "But behaviour should be, apply L/P/C only to hits selected by the checkboxes. Then it will be well-behaved."

Ah, I forgot about this one. I'm going to fix this ASAP.

**Comment by phraenquex** [comment] 2022-01-14 14:33
Thanks Anton!
@boriskovar-m2ms are you deploying these tickets on the test server?  Because we used to be able to give you feedback on UI things almost instantly - I'm desperate to have that back.

**Comment by phraenquex** [comment] 2022-02-01 07:24
This is great!
Still a bug - but create a new ticket if it's not a quick fix:
In Mpro, click "select all hits", then click "L".  It loads _very_ fast (GREAT!) but the [L] buttons in LHS are not all checked, and not all hits are selected.

**Closed** 2022-02-10 11:26 UTC
Labels: bug, E1 - GUI, MS 2022-01-01, MS 2022-02-10

**Comment by NikolaStryckova** [comment] 2022-02-16 10:55
Test steps:
- opening the Mpro target - result: OK,
- show all hits - result:  OK,
- select all hits (324) - result:  OK, 
- select "L" - system informs us that displaying of 324 may take a long time - result:  OK, all hits are checked and all "L" buttons are checked,

**Comment by rsanchezgarc** [comment] 2022-02-24 11:33
There are still some bugs
Steps:
1) Open Mpro (with log-in)
2) Select all hits
3) Click L and P to hide the predefined example.
4) Click L to show all ligands and say ok in the dialog.
## Then, some of the previously selected hits using select all hits become unselected
5) Clicking L again won't hide all displayed molecules, since some of then were magically unselected.

**Comment by boriskovar-m2ms** [comment] 2022-02-25 07:44
I think I fixed this issue. The problem was that clicking L or other buttons (P, C etc.) (global ones or ones on single hit) would also select all the tags associated with given hit in the Hit List Filter. This was done deliberately and I don't know why. I was thinking really hard why would anyone want this kind of behavior. I disabled this functionality.
